export const zhCN = {
    title: "月夜拾光",
    englishTitle: "MOONLIT GARDEN",
    subtitle: "把散落的微光，带回月亮身边",
    start: "开始拾光",
    again: "再游一次",
    resume: "继续漫游",
    pause: "暂停",
    readyTip: "收集萤火  ·  避开暗荆  ·  点亮花朵",
    controlTip: "拖动光灵移动  ·  点击月光波驱散暗荆",
    keyboardTip: "电脑可用 WASD / 方向键移动，空格释放月光波",
    pulse: "月光波",
    pulseReady: "已充能",
    score: "微光",
    best: "最佳",
    time: "时间",
    combo: "连拾",
    won: "月色正好",
    lost: "光还会再来",
    pauseTitle: "月夜暂歇",
    wonTip: "你守护了这座发光的花园",
    lostTip: "再走一程，月光仍在等你",
    goal: "坚持 60 秒，收集更多微光",
    hearts: "花瓣",
    scoreUnit: "分",
    secondsUnit: "秒",
    brand: "A LITTLE NIGHT ADVENTURE",
    badge: "01 / 花园之夜"
} as const;
